### ISSUE TITLE
using OVMF with efidisk, does not boot into iso

### ISSUE THREAD

**Issue by haup** [romantomjak/packer-proxmox-template#3]
Have you tried to use to change the bios type to OVMF? I tried the following lines

...
    machine = "q35"
    bios = "ovmf"
    os = "l26"
...
    efi_config {
        efi_storage_pool = "local"
        pre_enrolled_keys = true
        efi_type = "4m"
    }
...

**Comment by haup** [comment]
Somehow the vm boots into uefi, without any changes, after a reboot it´s starts the debian cd, but then without the preseed...

**Comment by romantomjak** [comment]
👋  I don't have any plans on trying that out myself, but I'll accept contributions if you find out the root cause 🙏
